apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tekton-chatops-task
spec:
  inputs:
    resources:
      - name: repo
        type: git
      - name: pr
        type: pullRequest
    params:
      - name: comment
        type: string
  outputs:
    resources:
      - name: pr
        type: pullRequest
  steps:
    - name: copy-pr
      image: ubuntu
      command: ["/bin/sh"]
      args:
        - -c
        - cp -r /workspace/pr/ /workspace/output/
    - name: run-command
      image: gcr.io/cloud-builders/git
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -ex
          # Get the PR number from the PR URL.
          prurl="$(inputs.resources.pr.url)"
          prNum=$(echo "$prurl" | awk -F/ '{print $NF}')
          comment="$(inputs.params.comment)"
          msg="no msg"
          case $comment in
            "/test" )
              cd /workspace/repo
              msg="TESTED"
            /chatbot* )
              msg="Usage: /chatbot \<command\>. Current commands are: test";;
            * )
              echo "skipping command $comment, does not start with /test";;
          esac
          if [[ ! -z "$msg" ]]; then
            echo "$msg" > /workspace/output/pr/comments/new
          fi
