apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-chatops-pipeline
spec:
  params:
    - name: comment
    - name: prid
    - name: reponame
    - name: prorg
    - name: branch
  tasks:
    - name: perform-chatops-command
      taskRef:
        name: tekton-chatops-gitopscli-task
      params:
        - name: comment
          value: $(params.comment)
        - name: prid
          value: $(params.prid)
        - name: reponame
          value: $(params.reponame)
        - name: prorg
          value: $(params.prorg)
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tekton-chatops-gitopscli-task
spec:
  inputs:
    params:
      - name: comment
      - name: prid
      - name: reponame
      - name: prorg
      - name: gitopscli-version
        default: v2.1.0
      - name: branch
        default: master
  stepTemplate:
    envFrom:
      - secretRef:
          name: github
  steps:
    - name: run-command
      image: baloiseincubator/gitopscli:$(inputs.params.gitopscli-version)
      script: |
        if [ $(inputs.params.comment) = "/test" ]; then
          gitopscli add-pr-comment \
          --username joachimprinzbach \
          --password $token \
          --git-provider github \
          --git-provider-url https://github.com/ \
          --organisation $(inputs.params.prorg) \
          --repository-name $(inputs.params.reponame) \
          --text='You can <br>use the command `/ping`' \
          --pr-id $(inputs.params.prid)
        elif [ $(inputs.params.comment) = "/preview" ]; then
          gitopscli create-preview \
          --username joachimprinzbach \
          --password $token \
          --git-provider github \
          --git-provider-url https://github.com/ \
          --organisation $(inputs.params.prorg) \
          --repository-name $(inputs.params.reponame) \
          --branch $(inputs.params.branch) \
          --pr-id $(inputs.params.prid) \
          --create-pr \
          --auto-merge
        elif [ $(inputs.params.comment) = "/undeploy" ]; then
          gitopscli delete-preview \
          --username joachimprinzbach \
          --password $token \
          --git-provider github \
          --git-provider-url https://github.com/ \
          --organisation $(inputs.params.prorg) \
          --repository-name $(inputs.params.reponame) \
          --branch $(inputs.params.branch) \
          --create-pr \
          --auto-merge
        elif [ $(inputs.params.comment) = "/help" ]; then
          gitopscli add-pr-comment \
          --username joachimprinzbach \
          --password $token \
          --git-provider github \
          --git-provider-url https://github.com/ \
          --organisation $(inputs.params.prorg) \
          --repository-name $(inputs.params.reponame) \
          --text='Need help? Find the docs, examples and a F.A.Q.: [Baloise Incubator: GitOps Cli](https://baloise-incubator.github.io/gitopscli/)' \
          --pr-id $(inputs.params.prid)
        else
          echo $(inputs.params.comment)
        fi
